package translateit2.fileloader;

public enum FileLoadError {
    CANNOT_CREATE_UPLOAD_DIRECTORY,
    CANNOT_READ_FILE,
    CANNOT_READ_LANGUAGE_FROM_FILE_NAME,
    CANNOT_UPLOAD_FILE,
    FILE_NOT_FOUND,
    FILE_TOBELOADED_IS_EMPTY,
    IMPROPER_EXTENSION_IN_FILE_NAME

}
