package translateit2.fileloader;

public enum FileLoadError {
    CANNOT_CREATE_UPLOAD_DIRECTORY,
    CANNOT_CREATE_PERMANENT_DIRECTORY,
    CANNOT_MOVE_FILE,
    CANNOT_READ_LANGUAGE_FROM_FILE_NAME,
    CANNOT_READ_APPLICATION_NAME_FROM_FILE_NAME,
    CANNOT_READ_FILE,
    CANNOT_UPLOAD_FILE,
    FILE_NOT_FOUND,
    FILE_TOBELOADED_IS_EMPTY,
    IMPROPER_CHARACTERSET_IN_FILE,
    IMPROPER_EXTENSION_IN_FILE_NAME,
    IMPROPER_APPLICATION_NAME_IN_FILE_NAME,
    IMPROPER_LOCALE_IN_FILE_NAME,
    UNDEFINED_ERROR
}
